%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Copyright (c) 2019 Yi Zhang and The University of Texas at Austin 
%  
% Permission is hereby granted, free of charge, to any person obtaining a 
% copy of this software and associated documentation files (the
% "Software"), to deal in the Software without restriction, including 
% without limitation the rights to use, copy, modify, merge, publish, 
% distribute, sublicense, and/or sell copies of the Software, and to permit
% persons to whom the Software is furnished to do so, subject to the 
% following conditions:
% 
% The above copyright notice and this permission notice shall be included
% in all copies or substantial portions of the Software.
% 
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
% OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
% MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
% NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
% DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR 
% OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE
% USE OR OTHER DEALINGS IN THE SOFTWARE.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% If you use this code or any (modified) part of it in any publication,
% please cite:
%
% Yi Zhang, Kartik Patel, Sanjay Shakkottai, and Robert W. Heath Jr.. 2019. 
% Side-information-aided Non-coherent Beam Alignment Design for Millimeter 
% Wave Systems. In MobiHoc '19: The Twentieth ACM International Symposium 
% on Mobile Ad Hoc Networking and Computing, July 02-05, 2019, Catania, 
% Italy. ACM, New York, NY, USA, 10 pages.
%
% Author: Yi Zhang
% Contact email: yi.zhang.cn@utexas.edu 
% Last modified: Apr. 2019
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Function description:
% This function plots arbitrary beam pattern generated by a ULA.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Input arguments:
% lambda: wavelength of 60.48 GHz signal.
% d: spacing distance between two neighboring antenna elements.
% F: a column vector which represents a beam pattern. Each element of the 
% vector denotes the phase state of the corresponding antenna element.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


function show_beam_pattern(lambda, d, F)
    [r, c] = size(F);
    Nt = r;
    figure
    for i = 1:1:c
        BeamformerQuant = F(:,i);
        rad_range = -pi/2:0.005:pi/2;
        gain = zeros(length(rad_range),1);
        ind = 1;
        for rad = rad_range
            Channel = transpose(exp(-1i*2*pi*d/lambda*sin(rad).*(0:1:Nt-1)));
            gain(ind) = abs(BeamformerQuant'*Channel);
            gain(find(gain<=0.001)) = 0.001;
            ind = ind + 1;
        end
        Gain_dB = 10*log10(gain*1000);
        M_Gain = max(Gain_dB);
        M_Gain_minus3dB = M_Gain-3;
        subplot(round(sqrt(c)),ceil(sqrt(c)),i);
        plot(rad2deg(rad_range),Gain_dB,'r');hold on;
        plot(rad2deg(rad_range),M_Gain_minus3dB*ones(1,length(rad_range)));hold on;
        plot(rad2deg(rad_range),M_Gain*ones(1,length(rad_range)));grid on;
    end
    figure
    for i = 1:1:c
        BeamformerQuant = F(:,i);
        rad_range = -pi/2:0.005:pi/2;
        gain = zeros(length(rad_range),1);
        ind = 1;
        for rad = rad_range
            Channel = transpose(exp(-1i*2*pi*d/lambda*sin(rad).*(0:1:Nt-1)));
            gain(ind) = abs(BeamformerQuant'*Channel);
            gain(find(gain<=0.001)) = 0.001;
            ind = ind + 1;
        end
        Gain_dB = 10*log10(gain*1000);
        M_Gain = max(Gain_dB);
        M_Gain_minus3dB = M_Gain-3;
        plot(rad2deg(rad_range),Gain_dB,'r');hold on;
        plot(rad2deg(rad_range),M_Gain_minus3dB*ones(1,length(rad_range)));hold on;
        plot(rad2deg(rad_range),M_Gain*ones(1,length(rad_range)));hold on;grid on;
    end
end